### ISSUE TITLE
Why no 'src' directory?

### ISSUE THREAD

**Issue by inklesspen** [pyrustic/setupinit#1]
In the readme, you link to the [Python Packaging User Guide](https://packaging.python.org/tutorials/packaging-projects/) and say this tool structures the package accordingly.

However, all the examples on that page have a `src` directory, following the best practice explained [here](https://hynek.me/articles/testing-packaging/). Why does this tool not do the same?

**Comment by pyrustic** [comment]
Hi ! Thank you for reporting this ! 

My [README](https://github.com/pyrustic/setupinit#readme) should have mentioned that the structure follows the [flat-layout](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#flat-layout).

I've read a bit of some discussions related to the "src" directory (and also this [one](https://github.com/pypa/setuptools/issues/1688)) and think it's worth doing some testing to see if I'll adopt this.

This package (**setupinit**) will be updated soon, I'm working on a big overhaul of the main repositories in this GitHub account, and I'm also thinking about a decent Git workflow to benefit from the contribution (better commit message with issue ref, branching, merging, etc.).

**Comment by pyrustic** [comment]
I have updated the tool and now a new project generated with it will include have the `src` directory. Moving from the flat layout to the `src` directory fixed a package discoverability issue in my IDE. Several of my projects aren't anymore following the flat layout !
